image: nnwww/haskell-stack-link-llvm3.7

stages:
  - build

build_job:
  stage: build
  script:
    - stack clean
    - stack install wcVector --split-objs --ghc-options="-fPIC -fllvm" --local-bin-path ./
    - upx --best --ultra-brute -o wcVector ./wcVector
  artifacts:
    paths:
      - ./wcVector
