image: nnwww/haskell-stack-link-llvm3.7

stages:
  - build

build_job:
  stage: build
  script:
    - stack clean
    - stack install wcVector --split-objs --ghc-options="-fPIC -fllvm" --local-bin-path $HOME
    - upx --best --ultra-brute $HOME/wcVector
  artifacts:
    paths:
      - $HOME/wcVector
